version: "3"

services:
  # Start API in local environment
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio-access-key-123"
      MINIO_ROOT_PASSWORD: "minio-secret-key-456"
    volumes:
      - minio-data:/data
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-pwd
      - MYSQL_DATABASE=synclip
      - MYSQL_USER=synclip
      - MYSQL_PASSWORD=synclip-pwd
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: tsingjyujing/synclip
    ports:
      - "8080:8080"
    environment:
      # do not set true in prod env
      SPRING_JPA_SHOW_SQL: "true"
      S3_ENDPOINT: "http://minio:9000"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/synclip"
    links:
      - db
      - minio
    depends_on:
      - db
      - minio

volumes:
  mysql-data:
  minio-data: