spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/synclip"
    username: "synclip"
    password: "synclip-pwd"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
s3:
  bucket: "synclip"
  endpoint: "http://localhost:9000"
  access-key: "minio-access-key-123"
  secret-key: "minio-secret-key-456"
synclip:
  clean-interval-ms: 3600000 # 1 hour
  expire-interval-secs: 7776000 # 90 days